//
// Created by JOSUE DAVID on 28/09/2022.
//

#ifndef PROYECTO_RECRUITMENT_TEAM_SJJ_SISTEMA_H
#define PROYECTO_RECRUITMENT_TEAM_SJJ_SISTEMA_H


class Sistema {

};


#endif //PROYECTO_RECRUITMENT_TEAM_SJJ_SISTEMA_H
